Repository Anjaliavv51/Retro, pull requests merged in 2024-10, with the labels that each got.

#16 Update menu.js - Streamline add cart process
  menu.js
Labels: good first issue, GSSOCEXTD, Level 1, Hacktoberfest Accepted

#17 update-button-issue#6
  Css-files/content.css
  Css-files/menu.css
  Css-files/style.css
  Html-files/Electronic.html
  style.css
Labels: enhancement, good first issue, GSSOCEXTD, Level 3, Hacktoberfest Accepted

#29 #15 Requirement of Proper Input Handling in Login/Register form
  Html-files/scriptsignup.js
  Html-files/signup.html
Labels: good first issue, GSSOCEXTD, Level 2, hacktoberfest-accepted

#59 All the pages have the updated UI of the contactus page
  Css-files/content.css
  Html-files/cart.html
  style.css
Labels: enhancement, good first issue, GSSOCEXTD, Level 3, hacktoberfest-accepted

#70 home.html-to-index.html
  Coverpage.html
  Html-files/Electronic.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/logged.html
  Html-files/menu.html
  Html-files/services.html
  Html-files/signed.html
  index.html
Labels: GSSOCEXTD, Level 3, hacktoberfest-accepted

#76 changed twitter logo to x logo in all html files
  Html-files/Electronic.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/menu.html
  Html-files/services.html
  index.html
Labels: bug, enhancement, good first issue, GSSOCEXTD, Level 2, hacktoberfest-accepted

#72 Enhanced Contact Section: Improved Form Design, Alignment, and Navigation Integration new
  Css-files/content.css
  Html-files/contact.html
Labels: enhancement, GSSOCEXTD, Level 2, hacktoberfest-accepted

#66 Prioritizing Image Loading
  cart.js
Labels: bug, GSSOCEXTD, Level 1, hacktoberfest-accepted

#86 The_navbar_position_changed
  Css-files/content.css
  Html-files/contact.html
Labels: bug, GSSOCEXTD, hacktoberfest-accepted

#87 Fixed Icon Overlap and Alphabet Input Allowed in Phone Number Field
  Css-files/content.css
  Html-files/contact.html
Labels: bug, enhancement, GSSOCEXTD, Level 1, hacktoberfest-accepted

#49 Redesign navbar of website to visible it clear
  style.css
Labels: bug, enhancement, GSSOCEXTD, Level 1, hacktoberfest-accepted

#88 enhanced footer icons color and size
  Coverpage.html
  Html-files/Electronic.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/menu.html
  Html-files/services.html
  style.css
Labels: enhancement, good first issue, GSSOCEXTD, Level 2, hacktoberfest-accepted

#42 [feature Request]: Want to improve design of cart page
  .vscode/settings.json
  Html-files/cart.html
Labels: enhancement, good first issue, GSSOCEXTD, Level 2, hacktoberfest-accepted

#122 Create CODE_OF_CONDUCT.md #115
  CODE_OF_CONDUCT.md
Labels: documentation, GSSOCEXTD, Level 1, hacktoberfest-accepted

#133 all the links in website updated and bugs resolved
  Html-files/cart.html
  Html-files/contact.html
  Html-files/menu.html
Labels: bug, GSSOCEXTD, hacktoberfest-accepted

#99 Making Contact Page Footer consistent with Home Page Footer
  Html-files/contact.html
Labels: enhancement, good first issue, GSSOCEXTD, Level 2, hacktoberfest-accepted

#171 Issue #109 solved. Renamed About section to Collections, And added new About page.
  Css-files/about.css
  Html-files/about.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/menu.html
  Html-files/services.html
  index.html
Labels: enhancement, good first issue, GSSOCEXTD, Level 2, hacktoberfest-accepted

#174 Payment UI Improved #165
  Favicon image/credit.avif
  Favicon image/google-pay-logo-2020.svg
  Favicon image/phonepe-icon.svg
  Html-files/payment2.html
Labels: enhancement, good first issue, GSSOCEXTD, Level 2, hacktoberfest-accepted

#175 Add Zoom Effect to Images with Class .menu on Hover
  Html-files/menu.html
Labels: enhancement, good first issue, GSSOCEXTD, Level 1, hacktoberfest-accepted

#160 Enhanced Signup page
  Css-files/signup1.css
Labels: enhancement, GSSOCEXTD, Level 3, hacktoberfest-accepted

#192 Enhanced the UI of the Navbar
  Css-files/about.css
Labels: enhancement, good first issue, GSSOCEXTD, Level 1, hacktoberfest-accepted

#227 In service section when we hover on last two cards text is not visible
  Css-files/content.css
  Html-files/services.html
Labels: bug, enhancement, good first issue, gssoc-ext, Level 1

#202 Added the homepage button on Sign up and Login pages
  Css-files/login1.css
  Css-files/signup1.css
  Html-files/login.html
  Html-files/signup.html
Labels: enhancement, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#224 updated-home_link
  Html-files/cart.html
Labels: bug, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#222 ✨[feature Request]: Changing Navbar #186
  Css-files/navbarstyles.css
  Html-files/Electronic.html
  Html-files/about.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/menu.html
  Html-files/services.html
  index.html
  style.css
Labels: enhancement, good first issue, gssoc-ext, Level 3, hacktoberfest-accepted

#234 Updated the retro logo on all pages and added the missing navbar elem…
  Html-files/Electronic.html
  Html-files/about.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/menu.html
  Html-files/services.html
Labels: enhancement, gssoc-ext, Level 1, hacktoberfest-accepted

#176 ✨[feature Request]: hover of the menu page does not looks good ith has hich chances of improvement #157
  Css-files/content.css
Labels: enhancement, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#232 Changes made in font style,size & alignment, Contact us area and print button
  index.html
  style.css
Labels: enhancement, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#247 issue#240 solved✨
  Css-files/signup1.css
  Html-files/login.html
  Html-files/signed.html
  Html-files/signup.html
Labels: enhancement, gssoc-ext, Level 1, hacktoberfest-accepted

#252 Added the hover and animation to login page
  Css-files/login1.css
Labels: enhancement, gssoc-ext, Level 2, hacktoberfest-accepted

#333 Update index.html
  index.html
Labels: enhancement, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#307 Collection's page box-modelling issue resolved
  Css-files/content.css
Labels: enhancement, good first issue, gssoc-ext, Level 2, hacktoberfest-accepted

#304 Implement Toggle Feature for Showing and Hiding Answers
  index.html
Labels: enhancement, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#338 🐞[bug]: On the login page there is no option to switch to signup page #318
  Html-files/login.html
  Html-files/signup.html
Labels: enhancement, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#389 Improved "Order Online" and "Track Your Order" Container
  index.html
  style.css
Labels: enhancement, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#372 improve the CoverPage and make it more attractive and aesthetic
  Coverpage.html
  RETRO.png
Labels: enhancement, gssoc-ext, Level 2, hacktoberfest-accepted

#343 social media icons added
  Css-files/about.css
  Css-files/content.css
  Html-files/about.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/menu.html
  Html-files/services.html
  index.html
  style.css
Labels: enhancement, good first issue, gssoc-ext, Level 2, hacktoberfest-accepted

#410 🐞[bug]: Without login accessing the cart page #321
  Html-files/cart.html
  Html-files/login.html
  Html-files/signup.html
Labels: good first issue, gssoc-ext, Level 2, hacktoberfest-accepted

#387 Create content_based_filtering.py
  content_based_filtering.py
Labels: good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#404 [documentation update]: README.md
  README.md
  about.png
  collection.png
  gssoc24.png
  hacktoberfest.png
  home.png
Labels: enhancement, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#472 ✨[feature Request]: Hover on question of FAQ will display answer
  index.html
Labels: enhancement, good first issue, gssoc-ext, Level 2, hacktoberfest-accepted

#488 alignment corrected
  Html-files/menu.html
Labels: enhancement, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#492 Fix inconsistent image stretching on customer opinion cards #452
  Css-files/content.css
Labels: enhancement, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#497 Responsiveness in Cart page
  Css-files/content.css
  Html-files/cart.html
Labels: gssoc-ext, Level 1, hacktoberfest-accepted

#500 Fixed misalignment of Buttons in Navbar issue ! #431
  index.html
Labels: bug, enhancement, gssoc-ext, Level 1, hacktoberfest-accepted

#504 Added Contributor's Page
  Css-files/contributor.css
  Html-files/Electronic.html
  Html-files/about.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/contributor.html
  Html-files/contributor.js
  Html-files/menu.html
  Html-files/services.html
  index.html
Labels: enhancement, good first issue, gssoc-ext, Level 2, hacktoberfest-accepted

#409 Add new column in cart for individual item total
  Html-files/cart.html
  Html-files/cart.js
Labels: enhancement, gssoc-ext, Level 1, hacktoberfest-accepted

#363 Create recommendation.py
  recommendation.py
Labels: gssoc-ext, Level 1, hacktoberfest-accepted

#580 Fix #578 Train Animation Direction Bug
  Html-files/about.html
Labels: enhancement, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#549 Responsiveness to all pages
  Css-files/about.css
  Css-files/content.css
  Css-files/login1.css
  Css-files/signup1.css
  Html-files/booknow.html
  Html-files/contact.html
  Html-files/forgot-pass.html
  Html-files/login.html
  Html-files/menu.html
  Html-files/services.html
  index.html
  style.css
Labels: enhancement, gssoc-ext, Level 3, hacktoberfest-accepted

#519 Add line on hover at footer
  Css-files/content.css
  Html-files/Electronic.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/menu.html
  Html-files/services.html
  index.html
  style.css
Labels: enhancement, gssoc-ext, Level 3, hacktoberfest-accepted

#511 Issue #505 solved : changed the styling of order online and collect order cards.
  index.html
  style.css
Labels: enhancement, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#355 count btn updated
  .vscode/settings.json
  Html-files/cart.html
Labels: enhancement, gssoc-ext, Level 1, hacktoberfest-accepted

#589 ADDED TRANSLATOR TOOL
  Coverpage.html
  Html-files/Electronic.html
  Html-files/about.html
  Html-files/booknow.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/contributor.html
  Html-files/forgot-pass.html
  Html-files/logged.html
  Html-files/login.html
  Html-files/menu.html
  Html-files/payment2.html
  Html-files/services.html
  Html-files/signed.html
  Html-files/signup.html
  index.html
Labels: enhancement, good first issue, gssoc-ext, Level 2, hacktoberfest-accepted

#597 solved issue #525
  Html-files/contact.html
Labels: enhancement, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#598 Created User generated content and reviews
  Html-files/reviews.html
  index.html
Labels: enhancement, good first issue, gssoc-ext, Level 3, hacktoberfest-accepted

#635 Make the Copyright year dynamic #311
  index.html
Labels: enhancement, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#800 Forgot Password shows incorrect email FORMAT
  Html-files/forgot-pass.html
Labels: bug, good first issue, gssoc-ext, Level 1, hacktoberfest-accepted

#770 Created Blog Page
  Html-files/blog.html
  index.html
Labels: enhancement, gssoc-ext, Level 3, hacktoberfest-accepted

#791 Popup Modal on Landing Page is Now Responsive on Smaller Screens
  Css-files/popup.css
  index.html
Labels: enhancement, good first issue, gssoc-ext, Level 1
