Repository Anjaliavv51/Retro, pull requests merged in 2025-01, with the labels that each got.

#847 Name to your commit
  index.html
Labels: BEGINNER, Winter Of Code 4.0

#855 🔗fix: Footer Copyright Year is Static and Not Dynamic
  Html-files/Electronic.html
  Html-files/about.html
  Html-files/blog.html
  Html-files/booknow.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/menu.html
  Html-files/reviews.html
  Html-files/services.html
Labels: good first issue

#872 Created feedback page with good features
  Css-files/feedback.css
  Html-files/feedback.html
  index.html
  script/feedback.js
Labels: good first issue, SWOC, ADVANCED
